global(workDirectory="/var/lib/rsyslog")

module(load="imuxsock")
module(load="imfile")

input(type="imfile"
      File="/var/log/squid/access.log"
      Tag="squid_access"
      Severity="info"
      Facility="local6"
      PersistStateInterval="200")

*.* @172.42.42.10:514
