@version: 4.2
options {
  chain_hostnames(no);
  use_dns(no);
  keep_hostname(yes);
  time_reopen(5);
  recv-time-zone("UTC");
  send-time-zone("UTC");
};

# ── Sources (listen) ──────────────────────────────────────────────────────────
source s_udp { udp(ip(0.0.0.0) port(514)); };
source s_tcp { tcp(ip(0.0.0.0) port(6514)); };

# ── Destinations (local files) ────────────────────────────────────────────────
destination d_all    { file("/var/log/syslog/all.log"    create-dirs(yes)); };

# ── Destinations (SIEM forwarding) ────────────────────────────────────────────
destination d_splunk_tcp {
  tcp("host.docker.internal" port(514)
      template("$UNIXTIME $HOST $PROGRAM: $MSG\n"));
};

# ── Log paths ────────────────────────────────────────────────────────────────
log { source(s_udp); destination(d_all); };
log { source(s_tcp); destination(d_all); };

# Forward to Splunk
log { source(s_udp); destination(d_splunk_tcp); };
log { source(s_tcp); destination(d_splunk_tcp); };
